In [4]:
len("1538456067000")

13

In [14]:
import numpy as np
import pandas as pd

pd.set_option('display.max_row',100)
pd.set_option('display.max_column',100)
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [7]:
!ls

PySQL_script.py       local_time_attack.csv
True.csv              testing_note.ipynb

In [50]:
data = pd.read_csv('local_time_attack.csv')

In [29]:
data

,Date,Start,End,Epoch Start,Epoch End,Type
0,10/3/18,2140,2206,1538602800000,1538604360000,CW of Freq
1,10/3/18,2336,2350,1538609760000,1538610600000,CW / pulse CW (+ CW on Glonass freq?)
2,10/4/18,140,202,1538617200000,1538618520000,GWN
3,10/4/18,205,209,1538618700000,1538618940000,GWN
4,10/4/18,217,243,1538619420000,1538620980000,GWN
5,10/4/18,244,259,1538621040000,1538621940000,GWN
6,10/4/18,301,329,1538622060000,1538623740000,GWN
7,10/4/18,334,348,1538624040000,1538710440000,FM CW
8,10/5/18,117,148,1538702220000,1538704080000,Sporadic Testing(Possible Test Data?)
9,10/5/18,148,208,1538704080000,1538705280000,GWN
10,10/5/18,211,230,1538705460000,1538706600000,CW L1
11,10/5/18,231,243,1538706660000,1538707380000,Jammer On/Off
12,10/5/18,245,257,1538707500000,1538708220000,GWN
13,10/5/18,259,317,1538708340000,1538698620000,Swept CW

In [30]:
data['Start_Hour'] = data['Start'].apply(lambda x: int(str(x)[:-2]))
data['Start_Minute'] = data['Start'].apply(lambda x: int(str(x)[-2:]))

data['End_Hour'] = data['End'].apply(lambda x: int(str(x)[:-2]))
data['End_Minute'] = data['End'].apply(lambda x: int(str(x)[-2:]))

In [32]:
data

,Date,Start,End,Epoch Start,Epoch End,Type,Start_Hour,Start_Minute,End_Hour,End_Minute
0,10/3/18,2140,2206,1538602800000,1538604360000,CW of Freq,21,40,22,6
1,10/3/18,2336,2350,1538609760000,1538610600000,CW / pulse CW (+ CW on Glonass freq?),23,36,23,50
2,10/4/18,140,202,1538617200000,1538618520000,GWN,1,40,2,2
3,10/4/18,205,209,1538618700000,1538618940000,GWN,2,5,2,9
4,10/4/18,217,243,1538619420000,1538620980000,GWN,2,17,2,43
5,10/4/18,244,259,1538621040000,1538621940000,GWN,2,44,2,59
6,10/4/18,301,329,1538622060000,1538623740000,GWN,3,1,3,29
7,10/4/18,334,348,1538624040000,1538710440000,FM CW,3,34,3,48
8,10/5/18,117,148,1538702220000,1538704080000,Sporadic Testing(Possible Test Data?),1,17,1,48
9,10/5/18,148,208,1538704080000,1538705280000,GWN,1,48,2,8
10,10/5/18,211,230,1538705460000,1538706600000,CW L1,2,11,2,30
11,10/5/18,231,243,1538706660000,1538707380000,Jammer On/Off,2,31,2,43
12,10/5/18,245,257,1538707500000,1538708220000,GWN,2,45,2,57
13,10/5/18,259,317,1538708340000,1538698620000,Swept CW,2,59,3,17

In [41]:
data_one = data.iloc[0]
data_end = data.iloc[-1]

In [36]:
single_min = (data_one['Epoch End'] - data_one['Epoch Start'])/((data_one['End_Hour'] * 60 + data_one['End_Minute']) - (data_one['Start_Hour'] * 60 + data_one['Start_Minute']))

In [38]:
single_min

60000.0

In [46]:
start_epoch = data_one['Epoch Start'] - single_min * (data_one['End_Hour'] * 60 + data_one['End_Minute'])
end_epoch = start_epoch + single_min * 72 * 60

In [47]:
single_min * 72 * 60

259200000.0

In [48]:
start_epoch

1538523240000.0

In [49]:
end_epoch

1538782440000.0